"""Norway Norwegian GAAP (NRS/IFRS) chart of accounts.

NRS = Norsk RegnskapsStandard for private companies; IFRS for listed.
CIT = Corporate Income Tax (22% standard; 78% petroleum sector).
VAT (MVA) = 25% standard / 15% food / 12% transport.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class NOGAAPAccount:
    code: str
    name: str
    category: str
    subcategory: str
    normal_balance: str


NO_GAAP: list[NOGAAPAccount] = [
    # Assets 1xxx
    NOGAAPAccount("1000", "Kasse (Cash on Hand)", "Asset", "Cash and Cash Equivalents", "Debit"),
    NOGAAPAccount("1010", "DNB Business Account", "Asset", "Cash and Cash Equivalents", "Debit"),
    NOGAAPAccount("1011", "Nordea Business Account", "Asset", "Cash and Cash Equivalents", "Debit"),
    NOGAAPAccount("1012", "Sparebank Business Account", "Asset", "Cash and Cash Equivalents", "Debit"),
    NOGAAPAccount("1020", "Vipps / MobilePay Float", "Asset", "Cash and Cash Equivalents", "Debit"),
    NOGAAPAccount("1030", "Term Deposits <= 12 months", "Asset", "Short-term Investments", "Debit"),
    NOGAAPAccount("1031", "Term Deposits > 12 months", "Asset", "Long-term Investments", "Debit"),
    NOGAAPAccount("1100", "Kundefordringer (Accounts Receivable)", "Asset", "Trade Receivables", "Debit"),
    NOGAAPAccount("1101", "Tapsavsetning kundefordringer (Allowance for Doubtful Debts)", "Asset", "Trade Receivables", "Credit"),
    NOGAAPAccount("1102", "Fordringer konsern (Related-party Receivables)", "Asset", "Trade Receivables", "Debit"),
    NOGAAPAccount("1110", "Inngaende MVA (VAT Receivable)", "Asset", "Tax Receivables", "Debit"),
    NOGAAPAccount("1111", "MVA kompensasjon (VAT Refund Receivable)", "Asset", "Tax Receivables", "Debit"),
    NOGAAPAccount("1200", "Ferdigvarer (Finished Goods)", "Asset", "Inventories", "Debit"),
    NOGAAPAccount("1201", "Varer under tilvirkning (Work in Progress)", "Asset", "Inventories", "Debit"),
    NOGAAPAccount("1202", "Ravarar (Raw Materials)", "Asset", "Inventories", "Debit"),
    NOGAAPAccount("1203", "Nedskrivning varer (Inventory Write-down)", "Asset", "Inventories", "Credit"),
    NOGAAPAccount("1300", "Forskuddsbetalt leie (Prepaid Rent)", "Asset", "Prepayments", "Debit"),
    NOGAAPAccount("1301", "Forskuddsbetalt forsikring (Prepaid Insurance)", "Asset", "Prepayments", "Debit"),
    NOGAAPAccount("1302", "Forskuddsbetalt abonnement (Prepaid Subscriptions)", "Asset", "Prepayments", "Debit"),
    NOGAAPAccount("1310", "Andre kortsiktige fordringer (Other Current Assets)", "Asset", "Other Current Assets", "Debit"),
    NOGAAPAccount("1320", "Lan til aksjonarer (Loans to Shareholders)", "Asset", "Other Receivables", "Debit"),
    NOGAAPAccount("1330", "Reiseforskudd ansatte (Staff Advances)", "Asset", "Other Receivables", "Debit"),
    NOGAAPAccount("1340", "Skattefunn tilgodehavende (SkatteFUNN Tax Credit Receivable)", "Asset", "Tax Receivables", "Debit"),
    NOGAAPAccount("1500", "Tomter og bygninger Kostpris (Land and Buildings Cost)", "Asset", "Property Plant and Equipment", "Debit"),
    NOGAAPAccount("1501", "Tomter Avskrivninger (Land and Buildings Accum Depreciation)", "Asset", "Property Plant and Equipment", "Credit"),
    NOGAAPAccount("1510", "Driftslosore maskiner Kostpris (Plant and Equipment Cost)", "Asset", "Property Plant and Equipment", "Debit"),
    NOGAAPAccount("1511", "Driftslosore maskiner Avskrivninger (Plant Accum Depreciation)", "Asset", "Property Plant and Equipment", "Credit"),
    NOGAAPAccount("1520", "Kontormobler Kostpris (Furniture Cost)", "Asset", "Property Plant and Equipment", "Debit"),
    NOGAAPAccount("1521", "Kontormobler Avskrivninger (Furniture Accum Depreciation)", "Asset", "Property Plant and Equipment", "Credit"),
    NOGAAPAccount("1530", "IT-utstyr Kostpris (Computer Hardware Cost)", "Asset", "Property Plant and Equipment", "Debit"),
    NOGAAPAccount("1531", "IT-utstyr Avskrivninger (Computer Hardware Accum Depreciation)", "Asset", "Property Plant and Equipment", "Credit"),
    NOGAAPAccount("1540", "Kjoretoy Kostpris (Motor Vehicles Cost)", "Asset", "Property Plant and Equipment", "Debit"),
    NOGAAPAccount("1541", "Kjoretoy Avskrivninger (Motor Vehicles Accum Depreciation)", "Asset", "Property Plant and Equipment", "Credit"),
    NOGAAPAccount("1550", "Bruksretteiendeler IFRS16 Kostpris (Right-of-Use Assets Cost)", "Asset", "Right-of-Use Assets", "Debit"),
    NOGAAPAccount("1551", "Bruksretteiendeler Avskrivninger (ROU Assets Accum Depreciation)", "Asset", "Right-of-Use Assets", "Credit"),
    NOGAAPAccount("1600", "Goodwill", "Asset", "Intangible Assets", "Debit"),
    NOGAAPAccount("1601", "Programvare Kostpris (Software Cost)", "Asset", "Intangible Assets", "Debit"),
    NOGAAPAccount("1602", "Programvare Amortisering (Software Accum Amortisation)", "Asset", "Intangible Assets", "Credit"),
    NOGAAPAccount("1603", "Patenter og varemerker Kostpris (Patents and Trademarks Cost)", "Asset", "Intangible Assets", "Debit"),
    NOGAAPAccount("1604", "Patenter Amortisering (Patents Accum Amortisation)", "Asset", "Intangible Assets", "Credit"),
    NOGAAPAccount("1700", "Aksjer notert (Equity Securities Listed)", "Asset", "Financial Assets", "Debit"),
    NOGAAPAccount("1701", "Aksjer unotert (Equity Securities Unlisted)", "Asset", "Financial Assets", "Debit"),
    NOGAAPAccount("1710", "Investering i datterselskap (Investment in Subsidiaries)", "Asset", "Financial Assets", "Debit"),
    NOGAAPAccount("1720", "Investering i tilknyttet selskap (Investment in Associates)", "Asset", "Financial Assets", "Debit"),
    NOGAAPAccount("1800", "Utsatt skattefordel (Deferred Tax Asset)", "Asset", "Deferred Tax", "Debit"),
    # Liabilities 2xxx
    NOGAAPAccount("2010", "Leverandorgjeld (Accounts Payable)", "Liability", "Trade Payables", "Credit"),
    NOGAAPAccount("2011", "Gjeld konsern (Related-party Payables)", "Liability", "Trade Payables", "Credit"),
    NOGAAPAccount("2100", "Utgaende MVA (VAT Payable)", "Liability", "Tax Payables", "Credit"),
    NOGAAPAccount("2101", "Skyldig arbeidsgiveravgift (Employer NI Payable)", "Liability", "Tax Payables", "Credit"),
    NOGAAPAccount("2110", "Betalbar skatt (CIT Payable)", "Liability", "Tax Payables", "Credit"),
    NOGAAPAccount("2111", "Skattetrekk lonninger (PAYE Withholding Payable)", "Liability", "Tax Payables", "Credit"),
    NOGAAPAccount("2120", "Skyldige lonninger (Salaries Payable)", "Liability", "Payroll Payables", "Credit"),
    NOGAAPAccount("2121", "Feriepenger skyldig (Holiday Pay Accrual)", "Liability", "Employee Entitlements", "Credit"),
    NOGAAPAccount("2122", "OTP pensjon skyldig (Occupational Pension Payable)", "Liability", "Payroll Payables", "Credit"),
    NOGAAPAccount("2200", "Palopne kostnader (Accrued Expenses)", "Liability", "Accruals", "Credit"),
    NOGAAPAccount("2201", "Palopne revisjonskostnader (Accrued Audit Fees)", "Liability", "Accruals", "Credit"),
    NOGAAPAccount("2210", "Uopptjent inntekt (Deferred Revenue)", "Liability", "Deferred Income", "Credit"),
    NOGAAPAccount("2220", "Mottatte forskudd kunder (Customer Deposits)", "Liability", "Other Payables", "Credit"),
    NOGAAPAccount("2230", "Utbytte skyldig (Dividends Payable)", "Liability", "Other Payables", "Credit"),
    NOGAAPAccount("2300", "Kassekreditt (Bank Overdraft)", "Liability", "Borrowings", "Credit"),
    NOGAAPAccount("2310", "Banklan kortsiktig (Bank Loan Current)", "Liability", "Borrowings", "Credit"),
    NOGAAPAccount("2311", "Banklan langsiktig (Bank Loan Non-current)", "Liability", "Borrowings", "Credit"),
    NOGAAPAccount("2320", "Aksjonarslan (Shareholder Loan)", "Liability", "Borrowings", "Credit"),
    NOGAAPAccount("2330", "Leasinggjeld kortsiktig IFRS16 (Lease Liability Current)", "Liability", "Lease Liabilities", "Credit"),
    NOGAAPAccount("2331", "Leasinggjeld langsiktig IFRS16 (Lease Liability Non-current)", "Liability", "Lease Liabilities", "Credit"),
    NOGAAPAccount("2400", "Utsatt skatt (Deferred Tax Liability)", "Liability", "Deferred Tax", "Credit"),
    # Equity 3xxx
    NOGAAPAccount("3010", "Aksjekapital (Share Capital)", "Equity", "Issued Capital", "Credit"),
    NOGAAPAccount("3020", "Overkursfond (Share Premium)", "Equity", "Issued Capital", "Credit"),
    NOGAAPAccount("3030", "Opptjent egenkapital (Retained Earnings BF)", "Equity", "Retained Earnings", "Credit"),
    NOGAAPAccount("3040", "Arets resultat (Current Year Profit or Loss)", "Equity", "Retained Earnings", "Credit"),
    NOGAAPAccount("3050", "Annen egenkapital (Other Comprehensive Income Reserve)", "Equity", "Reserves", "Credit"),
    NOGAAPAccount("3060", "Oppskrivningsfond (Asset Revaluation Reserve)", "Equity", "Reserves", "Credit"),
    NOGAAPAccount("3070", "Utbytte (Dividends Declared)", "Equity", "Retained Earnings", "Debit"),
    # Revenue 4xxx
    NOGAAPAccount("4010", "Salg av varer (Sales of Goods)", "Revenue", "Operating Revenue", "Credit"),
    NOGAAPAccount("4011", "Salgsreturer (Sales Returns)", "Revenue", "Operating Revenue", "Debit"),
    NOGAAPAccount("4020", "Driftsinntekter tjenester (Service Revenue)", "Revenue", "Operating Revenue", "Credit"),
    NOGAAPAccount("4030", "Leieinntekter (Rental Income)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4040", "Renteinntekter (Interest Income)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4050", "Utbytte mottatt (Dividend Income)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4060", "Gevinst salg eiendeler (Gain on Disposal of Assets)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4070", "Valutagevinst (Foreign Exchange Gain)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4080", "Tilskudd Innovasjon Norge (Innovation Norway Grants)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4090", "SkatteFUNN tilgodehavende (RD Tax Credit Income)", "Revenue", "Other Income", "Credit"),
    NOGAAPAccount("4100", "Andre inntekter (Miscellaneous Income)", "Revenue", "Other Income", "Credit"),
    # Expenses 5xxx
    NOGAAPAccount("5010", "Varekostnad (Cost of Goods Sold)", "Expense", "Cost of Sales", "Debit"),
    NOGAAPAccount("5020", "Direkte lonnskostnader (Direct Labour)", "Expense", "Cost of Sales", "Debit"),
    NOGAAPAccount("5030", "Produksjonsoverhead (Manufacturing Overhead)", "Expense", "Cost of Sales", "Debit"),
    NOGAAPAccount("5100", "Lonnskostnader (Salaries and Wages)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5101", "Arbeidsgiveravgift (Employer National Insurance)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5102", "OTP pensjon arbeidsgiver (Occupational Pension Employer)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5103", "Feriepenger (Holiday Pay Expense)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5104", "Yrkesskadeforsikring (Occupational Injury Insurance)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5105", "Personalforsikring (Staff Benefits)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5106", "Kompetanseheving ansatte (Staff Training)", "Expense", "Staff Costs", "Debit"),
    NOGAAPAccount("5200", "Husleie (Rent)", "Expense", "Premises Costs", "Debit"),
    NOGAAPAccount("5201", "Avskrivning bruksretteiendel (Depreciation ROU Asset)", "Expense", "Premises Costs", "Debit"),
    NOGAAPAccount("5202", "Rentekostnad leasinggjeld (Interest on Lease Liability)", "Expense", "Finance Costs", "Debit"),
    NOGAAPAccount("5210", "Strom og energi (Electricity and Energy)", "Expense", "Premises Costs", "Debit"),
    NOGAAPAccount("5211", "Renhold og vedlikehold (Cleaning and Maintenance)", "Expense", "Premises Costs", "Debit"),
    NOGAAPAccount("5300", "Revisjonshonorarer (Audit Fees)", "Expense", "Professional Fees", "Debit"),
    NOGAAPAccount("5301", "Regnskapshonorar (Accounting Fees)", "Expense", "Professional Fees", "Debit"),
    NOGAAPAccount("5302", "Juridiske honorarer (Legal Fees)", "Expense", "Professional Fees", "Debit"),
    NOGAAPAccount("5303", "Konsulenthonorarer (Consulting Fees)", "Expense", "Professional Fees", "Debit"),
    NOGAAPAccount("5400", "Avskrivning driftsmidler (Depreciation PPE)", "Expense", "Depreciation and Amortisation", "Debit"),
    NOGAAPAccount("5401", "Amortisering immaterielle eiendeler (Amortisation Intangibles)", "Expense", "Depreciation and Amortisation", "Debit"),
    NOGAAPAccount("5402", "Nedskrivning (Impairment Loss)", "Expense", "Depreciation and Amortisation", "Debit"),
    NOGAAPAccount("5500", "Rentekostnader banklan (Interest Expense Bank Loans)", "Expense", "Finance Costs", "Debit"),
    NOGAAPAccount("5501", "Bankgebyrer (Bank Charges)", "Expense", "Finance Costs", "Debit"),
    NOGAAPAccount("5600", "Betalbar skattekostnad (CIT Expense)", "Expense", "Taxation", "Debit"),
    NOGAAPAccount("5601", "Utsatt skattekostnad (Deferred Tax Expense or Credit)", "Expense", "Taxation", "Debit"),
    NOGAAPAccount("5700", "Markedsforing og reklame (Marketing and Advertising)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5701", "Reise og representasjon (Travel and Entertainment)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5702", "IT og programvareabonnement (IT Subscriptions and SaaS)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5703", "Kontorrekvisita (Office Supplies)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5704", "Forsikringspremier (Insurance Premiums)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5705", "Valutatap (Foreign Exchange Loss)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5706", "Tap pa fordringer (Bad Debt Written Off)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5707", "Telekommunikasjon (Telecommunication Expenses)", "Expense", "Other Operating Expenses", "Debit"),
    NOGAAPAccount("5708", "Diverse kostnader (Miscellaneous Expenses)", "Expense", "Other Operating Expenses", "Debit"),
]
