"""Portugal SNC (Sistema de Normalização Contabilística) chart of accounts.

SNC is the Portuguese accounting standards system, aligned with EU Directives
and IFRS principles. Introduced by Decreto-Lei n.º 158/2009.
IRC = Imposto sobre o Rendimento das Pessoas Coletivas (Corporate Income Tax).
IVA = Imposto sobre o Valor Acrescentado (VAT).
IRS = Imposto sobre o Rendimento das Pessoas Singulares (Personal Income Tax).
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class SNCAccount:
    code: str
    name: str
    category: str  # Asset | Liability | Equity | Revenue | Expense
    subcategory: str
    normal_balance: str  # Debit | Credit


PT_SNC: list[SNCAccount] = [
    # ── Class 1 — Financial means (Meios Financeiros Líquidos) ──────────────
    SNCAccount("11", "Caixa", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("111", "Caixa Principal", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("112", "Caixa Subsidiária", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("12", "Depósitos à Ordem", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("121", "Millennium BCP — Conta à Ordem", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("122", "Caixa Geral de Depósitos — Conta à Ordem", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("123", "BPI — Conta à Ordem", "Asset", "Cash and Cash Equivalents", "Debit"),
    SNCAccount("13", "Outros Depósitos Bancários", "Asset", "Short-term Investments", "Debit"),
    SNCAccount("131", "Depósitos a Prazo", "Asset", "Short-term Investments", "Debit"),
    SNCAccount("14", "Outros Instrumentos Financeiros", "Asset", "Financial Assets", "Debit"),

    # ── Class 2 — Accounts receivable / payable (Contas a Receber/Pagar) ───
    SNCAccount("21", "Clientes", "Asset", "Accounts Receivable", "Debit"),
    SNCAccount("211", "Clientes c/c", "Asset", "Accounts Receivable", "Debit"),
    SNCAccount("212", "Clientes — Títulos a Receber", "Asset", "Accounts Receivable", "Debit"),
    SNCAccount("213", "Clientes — Cobranças Duvidosas", "Asset", "Accounts Receivable", "Debit"),
    SNCAccount("218", "Adiantamentos de Clientes", "Liability", "Customer Advances", "Credit"),
    SNCAccount("22", "Fornecedores", "Liability", "Accounts Payable", "Credit"),
    SNCAccount("221", "Fornecedores c/c", "Liability", "Accounts Payable", "Credit"),
    SNCAccount("222", "Fornecedores — Títulos a Pagar", "Liability", "Accounts Payable", "Credit"),
    SNCAccount("228", "Adiantamentos a Fornecedores", "Asset", "Prepayments", "Debit"),
    SNCAccount("23", "Pessoal", "Liability", "Payroll Liabilities", "Credit"),
    SNCAccount("231", "Remunerações a Pagar", "Liability", "Payroll Liabilities", "Credit"),
    SNCAccount("232", "Adiantamentos ao Pessoal", "Asset", "Prepayments", "Debit"),
    SNCAccount("24", "Estado e Outros Entes Públicos", "Liability", "Tax Liabilities", "Credit"),
    SNCAccount("241", "IRS Retido na Fonte", "Liability", "Tax Liabilities", "Credit"),
    SNCAccount("242", "Retenções Segurança Social", "Liability", "Tax Liabilities", "Credit"),
    SNCAccount("243", "IVA", "Liability", "VAT Liabilities", "Credit"),
    SNCAccount("2431", "IVA Suportado", "Asset", "VAT Receivables", "Debit"),
    SNCAccount("2432", "IVA Dedutível", "Asset", "VAT Receivables", "Debit"),
    SNCAccount("2433", "IVA Liquidado", "Liability", "VAT Liabilities", "Credit"),
    SNCAccount("2434", "IVA Regularizações a Favor da Empresa", "Asset", "VAT Receivables", "Debit"),
    SNCAccount("2435", "IVA Regularizações a Favor do Estado", "Liability", "VAT Liabilities", "Credit"),
    SNCAccount("2436", "IVA a Pagar", "Liability", "VAT Liabilities", "Credit"),
    SNCAccount("2437", "IVA a Recuperar", "Asset", "VAT Receivables", "Debit"),
    SNCAccount("244", "IRC", "Liability", "Tax Liabilities", "Credit"),
    SNCAccount("245", "Impostos Diferidos", "Liability", "Deferred Tax", "Credit"),
    SNCAccount("246", "Tributos de Autarquias Locais (IMI/IMT)", "Liability", "Tax Liabilities", "Credit"),
    SNCAccount("25", "Financiamentos Obtidos", "Liability", "Borrowings", "Credit"),
    SNCAccount("251", "Financiamentos de Associadas", "Liability", "Borrowings", "Credit"),
    SNCAccount("252", "Financiamentos de Participadas", "Liability", "Borrowings", "Credit"),
    SNCAccount("26", "Acionistas / Sócios", "Equity", "Shareholder Equity", "Credit"),
    SNCAccount("261", "Acionistas c/c", "Equity", "Shareholder Current Account", "Credit"),
    SNCAccount("262", "Quotas não Liberadas", "Equity", "Share Capital", "Credit"),
    SNCAccount("27", "Outras Contas a Receber e a Pagar", "Asset", "Other Receivables", "Debit"),
    SNCAccount("271", "Fornecedores de Investimentos", "Liability", "Investment Payables", "Credit"),
    SNCAccount("272", "Devedores e Credores por Acréscimos", "Asset", "Accruals", "Debit"),
    SNCAccount("278", "Outros Devedores e Credores", "Asset", "Other Receivables", "Debit"),
    SNCAccount("28", "Diferimentos", "Asset", "Prepayments", "Debit"),
    SNCAccount("281", "Gastos a Diferir", "Asset", "Deferred Expenses", "Debit"),
    SNCAccount("282", "Rendimentos a Diferir", "Liability", "Deferred Revenue", "Credit"),

    # ── Class 3 — Inventories (Inventários e Ativos Biológicos) ─────────────
    SNCAccount("31", "Compras", "Expense", "Purchases", "Debit"),
    SNCAccount("311", "Mercadorias", "Expense", "Purchases", "Debit"),
    SNCAccount("312", "Matérias-Primas, Subsidiárias e de Consumo", "Expense", "Purchases", "Debit"),
    SNCAccount("32", "Mercadorias", "Asset", "Inventories", "Debit"),
    SNCAccount("33", "Matérias-Primas, Subsidiárias e de Consumo", "Asset", "Inventories", "Debit"),
    SNCAccount("34", "Produtos Acabados e Intermédios", "Asset", "Inventories", "Debit"),
    SNCAccount("35", "Subprodutos, Desperdícios, Resíduos e Refugos", "Asset", "Inventories", "Debit"),
    SNCAccount("36", "Produtos e Trabalhos em Curso", "Asset", "Inventories", "Debit"),
    SNCAccount("37", "Ativos Biológicos", "Asset", "Biological Assets", "Debit"),
    SNCAccount("38", "Reclassificação e Regularização de Inventários", "Expense", "Inventory Adjustments", "Debit"),
    SNCAccount("39", "Perdas por Imparidade Acumuladas", "Asset", "Impairment", "Credit"),

    # ── Class 4 — Non-current assets (Investimentos) ────────────────────────
    SNCAccount("41", "Investimentos Financeiros", "Asset", "Financial Investments", "Debit"),
    SNCAccount("411", "Participações Financeiras — Método de Equivalência Patrimonial", "Asset", "Financial Investments", "Debit"),
    SNCAccount("412", "Participações Financeiras — Outros Métodos", "Asset", "Financial Investments", "Debit"),
    SNCAccount("413", "Outros Investimentos Financeiros", "Asset", "Financial Investments", "Debit"),
    SNCAccount("42", "Propriedades de Investimento", "Asset", "Investment Properties", "Debit"),
    SNCAccount("43", "Ativos Fixos Tangíveis", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("431", "Terrenos e Recursos Naturais", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("432", "Edifícios e Outras Construções", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("433", "Equipamento Básico", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("434", "Equipamento de Transporte", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("435", "Equipamento Administrativo", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("436", "Equipamentos Biológicos", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("437", "Outros Ativos Fixos Tangíveis", "Asset", "Property, Plant and Equipment", "Debit"),
    SNCAccount("438", "Depreciações Acumuladas", "Asset", "Accumulated Depreciation", "Credit"),
    SNCAccount("439", "Perdas por Imparidade Acumuladas (AFT)", "Asset", "Impairment", "Credit"),
    SNCAccount("44", "Ativos Intangíveis", "Asset", "Intangible Assets", "Debit"),
    SNCAccount("441", "Goodwill", "Asset", "Intangible Assets", "Debit"),
    SNCAccount("442", "Projetos de Desenvolvimento", "Asset", "Intangible Assets", "Debit"),
    SNCAccount("443", "Programas de Computador", "Asset", "Intangible Assets", "Debit"),
    SNCAccount("444", "Propriedade Industrial", "Asset", "Intangible Assets", "Debit"),
    SNCAccount("448", "Amortizações Acumuladas", "Asset", "Accumulated Amortisation", "Credit"),
    SNCAccount("45", "Investimentos em Curso", "Asset", "Capital Work in Progress", "Debit"),
    SNCAccount("451", "Investimentos Financeiros em Curso", "Asset", "Capital Work in Progress", "Debit"),
    SNCAccount("452", "Propriedades de Investimento em Curso", "Asset", "Capital Work in Progress", "Debit"),
    SNCAccount("453", "Ativos Fixos Tangíveis em Curso", "Asset", "Capital Work in Progress", "Debit"),
    SNCAccount("454", "Ativos Intangíveis em Curso", "Asset", "Capital Work in Progress", "Debit"),

    # ── Class 5 — Equity (Capital, Reservas e Resultados Transitados) ───────
    SNCAccount("51", "Capital", "Equity", "Share Capital", "Credit"),
    SNCAccount("511", "Capital Subscrito", "Equity", "Share Capital", "Credit"),
    SNCAccount("52", "Ações (Quotas) Próprias", "Equity", "Treasury Shares", "Debit"),
    SNCAccount("53", "Outros Instrumentos de Capital Próprio", "Equity", "Other Equity Instruments", "Credit"),
    SNCAccount("54", "Prémios de Emissão", "Equity", "Share Premium", "Credit"),
    SNCAccount("55", "Reservas", "Equity", "Reserves", "Credit"),
    SNCAccount("551", "Reservas Legais", "Equity", "Legal Reserves", "Credit"),
    SNCAccount("552", "Outras Reservas", "Equity", "Other Reserves", "Credit"),
    SNCAccount("56", "Resultados Transitados", "Equity", "Retained Earnings", "Credit"),
    SNCAccount("57", "Ajustamentos em Ativos Financeiros", "Equity", "Other Comprehensive Income", "Credit"),
    SNCAccount("58", "Excedentes de Revalorização", "Equity", "Revaluation Surplus", "Credit"),
    SNCAccount("59", "Resultado Líquido do Período", "Equity", "Net Income", "Credit"),

    # ── Class 6 — Expenses (Gastos) ─────────────────────────────────────────
    SNCAccount("61", "CMVMC (Custo Mercadorias Vendidas e Mat. Consumidas)", "Expense", "Cost of Goods Sold", "Debit"),
    SNCAccount("611", "Mercadorias", "Expense", "Cost of Goods Sold", "Debit"),
    SNCAccount("612", "Matérias-Primas, Subsidiárias e de Consumo", "Expense", "Cost of Goods Sold", "Debit"),
    SNCAccount("62", "Fornecimentos e Serviços Externos", "Expense", "External Services", "Debit"),
    SNCAccount("621", "Subcontratos", "Expense", "External Services", "Debit"),
    SNCAccount("622", "Serviços Especializados", "Expense", "External Services", "Debit"),
    SNCAccount("6221", "Trabalhos Especializados", "Expense", "External Services", "Debit"),
    SNCAccount("6222", "Publicidade e Propaganda", "Expense", "Marketing Expenses", "Debit"),
    SNCAccount("6223", "Vigilância e Segurança", "Expense", "External Services", "Debit"),
    SNCAccount("6224", "Honorários", "Expense", "Professional Fees", "Debit"),
    SNCAccount("6225", "Comissões", "Expense", "External Services", "Debit"),
    SNCAccount("623", "Materiais", "Expense", "Materials", "Debit"),
    SNCAccount("624", "Energia e Fluidos", "Expense", "Utilities", "Debit"),
    SNCAccount("625", "Deslocações, Estadas e Transportes", "Expense", "Travel Expenses", "Debit"),
    SNCAccount("626", "Serviços Diversos", "Expense", "Miscellaneous Services", "Debit"),
    SNCAccount("63", "Gastos com o Pessoal", "Expense", "Personnel Costs", "Debit"),
    SNCAccount("631", "Remunerações dos Órgãos Sociais", "Expense", "Director Remuneration", "Debit"),
    SNCAccount("632", "Remunerações do Pessoal", "Expense", "Employee Wages", "Debit"),
    SNCAccount("633", "Benefícios Pós-Emprego", "Expense", "Post-Employment Benefits", "Debit"),
    SNCAccount("635", "Encargos sobre Remunerações (Segurança Social)", "Expense", "Social Security Contributions", "Debit"),
    SNCAccount("638", "Outros Gastos com o Pessoal", "Expense", "Personnel Costs", "Debit"),
    SNCAccount("64", "Gastos de Depreciação e de Amortização", "Expense", "Depreciation and Amortisation", "Debit"),
    SNCAccount("641", "Propriedades de Investimento", "Expense", "Depreciation", "Debit"),
    SNCAccount("642", "Ativos Fixos Tangíveis", "Expense", "Depreciation", "Debit"),
    SNCAccount("643", "Ativos Intangíveis", "Expense", "Amortisation", "Debit"),
    SNCAccount("65", "Perdas por Imparidade", "Expense", "Impairment Losses", "Debit"),
    SNCAccount("66", "Perdas em Subsidiárias, Associadas e Empreendimentos Conjuntos", "Expense", "Equity Method Losses", "Debit"),
    SNCAccount("67", "Provisões do Período", "Expense", "Provisions", "Debit"),
    SNCAccount("68", "Outros Gastos e Perdas", "Expense", "Other Expenses", "Debit"),
    SNCAccount("681", "Impostos e Taxas (excl. IRC/IVA)", "Expense", "Taxes and Levies", "Debit"),
    SNCAccount("682", "Gastos em Projetos de Investigação", "Expense", "R&D Expenses", "Debit"),
    SNCAccount("683", "Gastos com Instrumentos Financeiros", "Expense", "Financial Costs", "Debit"),
    SNCAccount("686", "Perdas em Inventários", "Expense", "Inventory Losses", "Debit"),
    SNCAccount("687", "Gastos e Perdas em Investimentos Financeiros", "Expense", "Investment Losses", "Debit"),
    SNCAccount("688", "Outros Gastos", "Expense", "Other Expenses", "Debit"),
    SNCAccount("69", "Gastos e Perdas de Financiamento", "Expense", "Finance Costs", "Debit"),
    SNCAccount("691", "Juros Suportados", "Expense", "Interest Expense", "Debit"),
    SNCAccount("692", "Diferenças de Câmbio Desfavoráveis", "Expense", "Exchange Losses", "Debit"),
    SNCAccount("698", "Outros Gastos e Perdas de Financiamento", "Expense", "Finance Costs", "Debit"),

    # ── Class 7 — Revenue (Rendimentos) ─────────────────────────────────────
    SNCAccount("71", "Vendas", "Revenue", "Sales Revenue", "Credit"),
    SNCAccount("711", "Mercadorias", "Revenue", "Sales Revenue", "Credit"),
    SNCAccount("712", "Produtos Acabados e Intermédios", "Revenue", "Sales Revenue", "Credit"),
    SNCAccount("713", "Subprodutos, Desperdícios, Resíduos e Refugos", "Revenue", "Sales Revenue", "Credit"),
    SNCAccount("718", "Descontos e Abatimentos em Vendas", "Revenue", "Sales Revenue", "Debit"),
    SNCAccount("72", "Prestações de Serviços", "Revenue", "Service Revenue", "Credit"),
    SNCAccount("721", "Serviços Prestados", "Revenue", "Service Revenue", "Credit"),
    SNCAccount("728", "Descontos e Abatimentos em Prestações de Serviços", "Revenue", "Service Revenue", "Debit"),
    SNCAccount("73", "Variações nos Inventários da Produção", "Revenue", "Inventory Changes", "Credit"),
    SNCAccount("74", "Trabalhos para a Própria Entidade", "Revenue", "Own Work Capitalised", "Credit"),
    SNCAccount("75", "Subsídios à Exploração", "Revenue", "Operating Grants", "Credit"),
    SNCAccount("76", "Reversões", "Revenue", "Reversals", "Credit"),
    SNCAccount("77", "Ganhos em Subsidiárias, Associadas e Empreendimentos Conjuntos", "Revenue", "Equity Method Gains", "Credit"),
    SNCAccount("78", "Outros Rendimentos e Ganhos", "Revenue", "Other Revenue", "Credit"),
    SNCAccount("781", "Rendimentos Suplementares", "Revenue", "Supplementary Revenue", "Credit"),
    SNCAccount("782", "Descontos de Pronto Pagamento Obtidos", "Revenue", "Prompt Payment Discounts", "Credit"),
    SNCAccount("783", "Recuperação de Dívidas", "Revenue", "Debt Recoveries", "Credit"),
    SNCAccount("784", "Alienações de Ativos", "Revenue", "Asset Disposal Gains", "Credit"),
    SNCAccount("788", "Outros Rendimentos", "Revenue", "Other Revenue", "Credit"),
    SNCAccount("79", "Juros e Rendimentos Similares", "Revenue", "Financial Revenue", "Credit"),
    SNCAccount("791", "Juros Obtidos", "Revenue", "Interest Income", "Credit"),
    SNCAccount("792", "Diferenças de Câmbio Favoráveis", "Revenue", "Exchange Gains", "Credit"),
    SNCAccount("798", "Outros Rendimentos e Ganhos de Financiamento", "Revenue", "Financial Revenue", "Credit"),

    # ── Class 8 — Net Income (Resultados) ───────────────────────────────────
    SNCAccount("81", "Resultado Antes de Impostos", "Equity", "Profit Before Tax", "Credit"),
    SNCAccount("811", "Resultado Antes de Impostos", "Equity", "Profit Before Tax", "Credit"),
    SNCAccount("82", "IRC — Imposto sobre o Rendimento do Período", "Expense", "Income Tax Expense", "Debit"),
    SNCAccount("821", "Imposto Estimado para o Período", "Expense", "Income Tax Expense", "Debit"),
    SNCAccount("822", "Imposto Diferido", "Expense", "Deferred Tax Expense", "Debit"),
    SNCAccount("89", "Resultado Líquido do Período", "Equity", "Net Income", "Credit"),
]
